apiVersion: v1
kind: ServiceAccount
metadata:
  name: seagles-sa
  namespace: security-tools
  labels:
    app: seagles-backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: seagles-role
  namespace: security-tools
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: seagles-role-binding
  namespace: security-tools
subjects:
- kind: ServiceAccount
  name: seagles-sa
  namespace: security-tools
roleRef:
  kind: Role
  name: seagles-role
  apiGroup: rbac.authorization.k8s.io
