apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seagles-data-pvc
  namespace: security-tools
  labels:
    app: seagles-backend
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
