package models

import (
	"database/sql"
	"encoding/json"
	"time"
)

// Alert represents a security alert generated by the system.
type Alert struct {
	ID             string          `json:"id" db:"id"`
	DeviceID       sql.NullString  `json:"device_id" db:"device_id"`
	Severity       string          `json:"severity" db:"severity"`
	AlertType      string          `json:"alert_type" db:"alert_type"`
	Title          string          `json:"title" db:"title"`
	Description    sql.NullString  `json:"description" db:"description"`
	TriggeredAt    time.Time       `json:"triggered_at" db:"triggered_at"`
	AcknowledgedAt sql.NullTime    `json:"acknowledged_at" db:"acknowledged_at"`
	IsAcknowledged bool            `json:"is_acknowledged" db:"is_acknowledged"`
	Metadata       json.RawMessage `json:"metadata" db:"metadata"`
}

// AlertJSON is a JSON-friendly representation of an Alert.
type AlertJSON struct {
	ID             string          `json:"id"`
	DeviceID       *string         `json:"device_id"`
	Severity       string          `json:"severity"`
	AlertType      string          `json:"alert_type"`
	Title          string          `json:"title"`
	Description    *string         `json:"description"`
	TriggeredAt    time.Time       `json:"triggered_at"`
	AcknowledgedAt *time.Time      `json:"acknowledged_at"`
	IsAcknowledged bool            `json:"is_acknowledged"`
	Metadata       json.RawMessage `json:"metadata,omitempty"`
}

// ToJSON converts an Alert to a JSON-friendly representation.
func (a *Alert) ToJSON() AlertJSON {
	aj := AlertJSON{
		ID:             a.ID,
		Severity:       a.Severity,
		AlertType:      a.AlertType,
		Title:          a.Title,
		TriggeredAt:    a.TriggeredAt,
		IsAcknowledged: a.IsAcknowledged,
		Metadata:       a.Metadata,
	}
	if a.DeviceID.Valid {
		aj.DeviceID = &a.DeviceID.String
	}
	if a.Description.Valid {
		aj.Description = &a.Description.String
	}
	if a.AcknowledgedAt.Valid {
		aj.AcknowledgedAt = &a.AcknowledgedAt.Time
	}
	return aj
}
